export const AIRCRAFT_MODEL_CONSTRAINTS = {
  NAME: { MIN_LENGTH: 2, MAX_LENGTH: 30 },
  CODE: { MIN_LENGTH: 2, MAX_LENGTH: 10 },
  MANUFACTURER: { MIN_LENGTH: 2, MAX_LENGTH: 20 },
  PASSENGERS: { MIN: 1, MAX: 400 },
  ENGINES: { MIN: 1, MAX: 6 }
} as const
